Repository ThinLineIT/CtrlF_Data, pull requests merged in 2021-06, with the labels that each got.

#24 Observable2
  iOS/Observable 2.md
Labels: LGTM

#30 What is React?
  React/What is React.md
  React/image/rendering process.png
Labels: LGTM

#21 Dijkstra Algorithm
  Algorithm/dijkstraAlgorithm.md
Labels: LGTM

#26 Android/MVC
  Android/MVC.md
  Android/img/MVCPackage.PNG
  Android/img/MVCProcess.PNG
Labels: LGTM

#34 Dynamic Programming.md
  Algorithm/Dynamic Programming.md
  Algorithm/img/DP_image.png
Labels: LGTM

#27 Android/MVP
  Android/MVP.md
  Android/img/MVPPackage.png
  Android/img/MVPProcess.png
Labels: LGTM

#28 Android/MVVM
  Android/MVVM.md
  Android/img/MVVMPackage.png
  Android/img/MVVMProcess.png
Labels: Review Requested

#29 Create MVC vs MVP vs MVVM.md
  Android/MVC vs MVP vs MVVM.md
Labels: LGTM

#35 Notification.md
  Android/Notification.md
Labels: LGTM

#7 Algorithm/huffman code
  Algorithm/HuffmanCode.md
  Algorithm/img/FrequencyByCharacter.png
  Algorithm/img/SortCharacterByFrequency.png
  Algorithm/img/result.png
  Algorithm/img/step2.png
  Algorithm/img/step3.png
  Algorithm/img/step4.png
Labels: LGTM

#37 Android/listview VS recyclerview
  Android/listview VS recyclerview.md
Labels: LGTM

#38 Android/recyclerview
  Android/recyclerview.md
Labels: LGTM

#33 Lifecycle about Class Component
  React/About lifecylce in class component.md
  React/image/lifecycle.jpeg
Labels: LGTM

#36 Algorithm/BFS
  Algorithm/BFS.md
  Algorithm/img/BFS_1.png
  Algorithm/img/BFS_2.png
  Algorithm/img/BFS_3.png
  Algorithm/img/BFS_4.png
  Algorithm/img/BFS_5.png
  Algorithm/img/BFS_6.png
  Algorithm/img/BFS_7.png
  Algorithm/img/BFS_Tree.png
  Algorithm/img/BFS_gjf.gjf
Labels: LGTM

#40 State Pattern.md
  DesignPattern/State Pattern.md
  DesignPattern/img/diagram_state.png
  DesignPattern/img/img_state.png
  DesignPattern/img/result_state.png
Labels: LGTM

#41 Oop/abstraction
  OOP/Abstraction.md
  OOP/img/Abstraction_Code_Result.png
  OOP/img/DogCatTiger.png
Labels: LGTM

#42 Network OSI7Layer
  Network/OSI7Layer.md
Labels: LGTM

#43 iOS Scheduler
  iOS/Scheduler.md
Labels: LGTM

#44 Database / Normalization
  database/Normalization.md
Labels: LGTM

#47 What is Jetpack Compose
  Android/What is Jetpack Compose.md
  Android/img/PreviewEx.png
Labels: LGTM

#13 N Queens Problem
  Algorithm/N_Queens_Problem.md
Labels: Change Requested

#11 Backtracking against Greedy algorithm
  Algorithm/Backtracking.md
Labels: Change Requested
