Repository ThinLineIT/CtrlF_Data, pull requests merged in 2021-07, with the labels that each got.

#54 Cache Memory.md
  OS/Cache Memory.md
  OS/img/img_cache.png
  OS/img/img_hit_ratio.png
Labels: LGTM

#59 Topology Sort
  Algorithm/Topology Sort.md
Labels: LGTM

#62 What is State
  React/What is State.md
  React/image/state_test.gif
Labels: LGTM

#67 Android/listview
  Android/listview.md
Labels: LGTM

#12 Algorithm/MergeSort
  Algorithm/MergeSort.md
  Algorithm/img/MergeSortConcept.png
  Algorithm/img/MergeSortConcept2.png
  Algorithm/img/StableSorting.jpeg
  Algorithm/img/UnstableSorting.jpeg
Labels: Review Requested

#66 Android/coroutine overview
  Android/Coroutine1.md
  Android/img/CoroutinelightWeight.png
  Android/img/Coroutinenonblocking.jpg
Labels: LGTM

#69 composing suspending function.md
  Android/Composing suspending func.md
Labels: Review Requested

#72 Floyd Warshall
  Algorithm/Floyd Warshall.md
Labels: Review Requested

#79 Moblie App Types
  ETC/Mobile App Types.md
Labels: LGTM, Review Requested

#81 What is Middleware?
  Network/Middleware.md
Labels: LGTM, Review Requested

#82 Create Template Method Pattern.md
  DesignPattern/Template Method Pattern.md
  DesignPattern/img/diagram_TemplateMethod.PNG
  DesignPattern/img/img_TemplateMethod.png
Labels: Review Requested

#83 Create Composite Pattern.md
  DesignPattern/Composite Pattern.md
  DesignPattern/img/Diagram_Composite.png
  DesignPattern/img/result_composite.png
Labels: Review Requested

#84 Create Decorator Pattern.md
  DesignPattern/Decorator Pattern.md
  DesignPattern/img/diagram_Decorator.png
Labels: Review Requested

#85 Create Strategy Pattern.md
  DesignPattern/Strategy Pattern.md
  DesignPattern/img/diagram_Strategy.png
  DesignPattern/img/img_Strategy.png
Labels: Review Requested

#73 Disjoint Sets
  Algorithm/Disjoint Sets.md
  Algorithm/img/DisjointSets_1.png
Labels: LGTM, Review Requested

#86 What are Cloud Computing Service Types?
  ETC/Cloud Computing Service Types.md
  ETC/img/Cloud_types_1.png
Labels: LGTM, Review Requested

#88 BitMask.md
  Algorithm/BitMask.md
  Algorithm/img/AND.png
  Algorithm/img/INIT.png
  Algorithm/img/NOT.png
  Algorithm/img/OR.png
  Algorithm/img/OR2.png
  Algorithm/img/SHIFT.png
  Algorithm/img/XOR.png
Labels: LGTM

#90 Trie.md
  DataStructure/Trie.md
  DataStructure/img/Trie.png
Labels: LGTM

#87 HeapSort.md
  Algorithm/HeapSort.md
  Algorithm/img/HeapSort1.png
  Algorithm/img/HeapSort2.png
  Algorithm/img/HeapSort3.png
Labels: LGTM

#68 Android/coroutineBasic
  Android/Coroutine Basics.md
Labels: Review Requested

#74 OOP/Inheritance
  OOP/Inheritance.md
  OOP/img/Inheritance_Result.png
  OOP/img/Parent&Child_Class.png
Labels: Review Requested

#76 OOP/Encapsulation
  OOP/Encapsulation.md
  OOP/img/ATM_Class.png
  OOP/img/Encapsulation_Result.png
  OOP/img/capsule.jpeg
Labels: Review Requested

#89 KMP.md
  Algorithm/KMP.md
  Algorithm/img/Atom.lnk
  Algorithm/img/kmp_example1.png
  Algorithm/img/kmp_example2.png
  Algorithm/img/kmp_example3.png
  Algorithm/img/kmp_fail1.png
  Algorithm/img/kmp_fail2.png
  Algorithm/img/kmp_fail3.png
  Algorithm/img/kmp_fail4.png
  Algorithm/img/kmp_fail5.png
  Algorithm/img/kmp_img1.png
  Algorithm/img/kmp_img10.png
  Algorithm/img/kmp_img11.png
  Algorithm/img/kmp_img12.png
  Algorithm/img/kmp_img13.png
  Algorithm/img/kmp_img14.png
  Algorithm/img/kmp_img15.png
  Algorithm/img/kmp_img16.png
  Algorithm/img/kmp_img2.png
  Algorithm/img/kmp_img3.5.png
  Algorithm/img/kmp_img3.png
  Algorithm/img/kmp_img4.png
  Algorithm/img/kmp_img5.png
  Algorithm/img/kmp_img6.png
  Algorithm/img/kmp_img7.png
  Algorithm/img/kmp_img8.png
  Algorithm/img/kmp_img9.png
Labels: Review Requested

#10 Android/handlerlooper
  Android/handlerlooper.md
Labels: Change Requested

#15 Graph Coloring
  Algorithm/Graph_Coloring.md
Labels: Change Requested

#103 Revise filename extension
  DesignPattern/img/diagram_TemplateMethod.png
Labels: Review Requested

#19 add Algorithm/Greedy.md
  Algorithm/Greedy.md
Labels: Change Requested

#98 Create Retrofit Basic1.md
  Android/Retrofit Basic1.md
Labels: Review Requested

#101 Android/coroutine cancellation
  Android/Coroutine Cancellation.md
Labels: LGTM

#46 OS / CPUScheduling
  OS/CPUscheduling.md
Labels: Change Requested, LGTM

#100 Create Retrofit Basic2.md
  Android/Retrofit Basic2.md
Labels: LGTM

#97 How Javascript works
  React/How Javascript works.md
  React/image/CallStack.png
  React/image/WebAPIs.png
Labels: Review Requested

#99 What is Euclidean Algorithm
  Algorithm/Euclidean Algorithm.md
Labels: Review Requested

#102 Create REST.md
  ETC/REST.md
Labels: Review Requested

#107 Create REST API.md
  ETC/REST API.md
Labels: Review Requested

#104 create onsaveinstancestate.md
  Android/onsaveinstancestate.md
Labels: Change Requested

#105 create twopointer.md
  Algorithm/twopointer.md
Labels: Change Requested
